// --------------------------------------------------------------------------------------------------------------------
// <copyright file="VlcDummyFactory.cs" company="Naos Project">
//    Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package Naos.Build.Conventions.VisualStudioProjectTemplates.Domain.Test (1.55.54)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.Vlc.Domain.Test
{
    using System;

    using FakeItEasy;

    using OBeautifulCode.AutoFakeItEasy;

    /// <summary>
    /// A Dummy Factory for types in <see cref="Domain"/>.
    /// </summary>
#if !NaosVlcSolution
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("Naos.Vlc.Domain.Test", "See package version number")]
    internal
#else
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Vlc")]
    public
#endif
    class VlcDummyFactory : DefaultVlcDummyFactory
    {
        public VlcDummyFactory()
        {
            /* Add any overriding or custom registrations here. */
        }
    }
}